Make tests pass on Rails 5.x
For some reason the test would fail with a

    Error:
    RouteMiddlewareTest#test_Redirect_instead_of_rewrite:
    NoMethodError: undefined method `url_for' for ActionController::Redirecting:Module
        actionpack (5.0.1) lib/action_controller/metal/redirecting.rb:118:in `_compute_redirect_to_location'
        actionpack (5.0.1) lib/action_dispatch/testing/assertions/response.rb:75:in `normalize_argument_to_redirection'
        actionpack (5.0.1) lib/action_dispatch/testing/assertions/response.rb:87:in `location_if_redirected'
        actionpack (5.0.1) lib/action_dispatch/testing/assertions/response.rb:82:in `generate_response_message'
        actionpack (5.0.1) lib/action_dispatch/testing/assertions/response.rb:29:in `assert_response'
        route_downcaser/test/integration/route_middleware_test.rb:30:in `block in <class:RouteMiddlewareTest>'

apparently caused by a bug in `assert_response`, potentially something missing
in the load path.

Doing it this way at least makes our tests pass, albeit with a slightly more
bare-metal syntax.